# Configuration file for single device setup example
[device.ob_lidar]
name = "ob_lidar"
# type can be single_line or multi_line
type = "single_line"
enable_heartbeat = true
max_heartbeat_fail_allowed = 3
heartbeat_interval_ms = 1000
option_timeout_ms = 3000


[device.ob_lidar.network]
single_port_mode = true
ip = "192.168.1.120"
protocol = "udp"
port = 2401
# if single_port_mode is true, the following ports are ignored
command_port = 2368
point_cloud_port = 2369
imu_port = 2370
log_port = 2371

[logging]
max_file_size = 10485760 # 10M
max_file_num = 10 # max file number is 10
log_file_dir = "/tmp"
console_log_level = "info"
file_log_level = "info"
log_to_console = true
log_to_file = true
